config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'home#index'

  get 'signup' => "users#new"
  post 'signup' => "users#create"
  get 'verify_email' => 'users#verify_email'
  
  get "/power" => "power#index"

  scope :invite do
    get "complete" => "guests#get_profile"
    post "complete" => "guests#complete_profile"
    get ":invite_for/:token" => "guests#new"
    post ":invite_for/:token" => "guests#send_email_otp", as: :new_guest
    get ":invite_for/verify_email/:token" => "guests#get_otp"
    post ":invite_for/verify_email/:token" => "guests#verify_email", as: :create_guest
    get ':invite_for/continue/:token/' => "guests#continue_as_existing_guest", as: :continue_as_existing_guest
  end
  get '/checkin/respond' => "checkin/checkins#respond"

  delete "guests/exit" => "guests#exit"

  constraints lambda { |req| req.format == :json } do
    # resources :users, only: [:update, :destroy]
    put "profile" => "users#update"
    delete "profile" => "users#destroy"

    resources :feedbacks, only: :create

    namespace :poker do
      resources :boards, only: [:index, :show, :create, :update, :destroy], param: :board_id do
        member do
          post 'archive'
          put 'rename'
          delete 'participant' => "boards#remove_participant"
          resources :issues, only: [:create, :destroy], param: :issue_id do
            member do
              put 'vote'
              put 'update_status'
              put 'clear_votes'
              post 'assign'
            end
          end
        end
      end
    end
    namespace :retro do
      resources :board, except: [:new, :edit], param: :board_id do
        member do
          put 'rename' => "board#rename"
          delete 'participant' => "board#remove_participant"
          resources :action_items, only: [:create, :destroy], param: :item_id do
            member do
              put 'toggle'
            end
          end
          resources :columns, only: [:create, :update, :destroy], param: :column_id do
            member do
              resources :cards, only: [:create, :update, :destroy], param: :card_id do
                member do
                  post 'comment' => "cards#add_comment"
                  delete 'comment' => "cards#remove_comment"
                  put 'rearrange'
                  post 'vote' => "cards#toggle_vote"
                end
              end
            end
          end
        end
      end
    end

    resources :checkins, only: [:index, :create, :show, :edit, :update, :destroy], controller: 'checkin/checkins', param: :checkin_id do
      member do
        post 'toggle_pause'
        post 'respond' => 'checkin/responses#set_answers'
        resources :issues, only: [:show], param: :issue_id, controller: 'checkin/issues'
      end
    end

    namespace :power do
      resources :users
      resources :features, param: :feature_id do
        member do
          post 'toggle'
        end
      end
    end

    scope :power do
      resources :feedbacks, only: :index
    end
  end

  constraints lambda { |req| req.format == :html && !req.path.starts_with?("/rails/active_storage") && !req.path.starts_with?("/power")} do
    get '*path' => 'main#index'
  end

  authenticate :user, lambda { |u| u.power_user? } do
    mount Sidekiq::Web => '/power/jobs'
    constraints lambda { |req| req.format == :html && req.path.starts_with?("/power") } do
      get '*path' => 'power#index'
    end
  end
  
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :parent_user, class_name: "User"
  has_many :retro_board_participants, class_name: "Retro::Participant", as: :participant
  has_many :retro_boards, through: :retro_board_participants,  source: :board 
  has_many :poker_board_participants, class_name: "Poker::Participant", as: :participant
  has_many :poker_boards, through: :poker_board_participants,  source: :board
  has_many :feedbacks, as: :feedback_by
  has_many :checkin_participants, class_name: "Checkin::Participant", as: :participant
  has_many :checkins, through: :checkin_participants,  source: :checkin

  delegate :can_access?, to: :parent_user

  def name_or_email
    name.blank? ? email : name
  end

  def avatar_url
    # return unless avatar.attached?
    # ENV['HOST'].chop + Rails.application.routes.url_helpers.rails_representation_url(avatar.variant(resize_to_limit: [180, 180]).processed, host: ENV['HOST'], only_path: true)
    return nil
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    
    @invite_for = params[:invite_for]
    @token = params[:token]
    case @invite_for
    when 'retro' then @board = Retro::Board.get_board_by_invitation_token(@token)
    when 'poker' then @board = Poker::Board.get_board_by_invitation_token(@token)
    else
      @invalid = true
      flash[:alert] = "Invalid invite link"
    end

    # TODO: DRY
    if current_resource.present? && @board.present?
      case @board.class.to_s
      when "Poker::Board"
        participant = Poker::Participant.where(board: @board, participant: current_resource, is_spectator: false).first_or_create!
        PokerBoardChannel.broadcast_to(@board,  {status: true, type: 'new_participant', participant: { id: participant.id, email: participant.participant.email, name: participant.participant.name } })
        redirect_to "/poker/board/#{@board.id}"
      when "Retro::Board"
        participant = Retro::Participant.where(board: @board, participant: current_resource).first_or_create!
        RetroBoardChannel.broadcast_to(@board,  {status: true, type: "new_participant", name: current_resource.name, id: current_resource.id, participant_id: participant.id })
        redirect_to retro_board_path(@board.id)
      else
        show_invitation_error("Invalid invitation link") and return
      end
    end
  end

  def get_profile
    @signature = params[:signature]
    parsed_sig = JSON.parse(Base64.decode64(@signature)) rescue nil
    show_complete_profile_error("Error") and return unless parsed_sig.present?
    if parsed_sig['origin'] == 'checkin'
      @response = Checkin::Response.from_token(parsed_sig['token'])
      show_complete_profile_error("Error") and return unless @response.present?
      @resource = @response.participant.participant
      if @resource.present?
      else
        show_complete_profile_error("Error") and return
      end
    end

  end

  def complete_profile
    @signature = params[:signature]
    parsed_sig = JSON.parse(Base64.decode64(@signature)) rescue nil
    show_complete_profile_error("Error") and return unless parsed_sig.present?
    if parsed_sig['origin'] == 'checkin'
      @response = Checkin::Response.from_token(parsed_sig['token'])
      show_complete_profile_error("Error") and return unless @response.present?
      @resource = @response.participant.participant
      if @resource.present?
        @resource.update!(name: params[:name].strip)
        redirect_to checkin_respond_path(email: @resource.email, token: parsed_sig['token'])
      else
        show_complete_profile_error("Error") and return
      end
    end
  end

  def send_email_otp
    @invite_for = params[:invite_for]
    @token = params[:token]
    case @invite_for
    when 'retro' then @board = Retro::Board.get_board_by_invitation_token(@token)
    when 'poker' then @board = Poker::Board.get_board_by_invitation_token(@token)
    else
      @invalid = true
      flash[:alert] = "Invalid invite link"
    end
    return unless validate_guest_params
    guest = Guest.where(email: guest_params[:email], parent_user_id: @board.created_by).first_or_initialize
    guest.name = guest_params[:name].strip
    guest.save!
    cookies.encrypted[:temp_gid] = guest.id
    GuestsMailer.send_email_otp(guest.id).deliver_now
    redirect_to create_guest_path(token: @token, invite_for: @invite_for)
  end

  def get_otp
    @invite_for = params[:invite_for]
    @token = params[:token]
    case @invite_for
    when 'retro' then @board = Retro::Board.get_board_by_invitation_token(@token)
    when 'poker' then @board = Poker::Board.get_board_by_invitation_token(@token)
    else
      @invalid = true
      flash[:alert] = "Invalid invite link"
    end
    @guest = Guest.where(id: cookies.encrypted[:temp_gid], parent_user_id: @board.created_by).where("email_otp_sent_at >= ?", 15.minutes.ago).take
    show_invitation_error("Invalid invite link") unless @guest.present?
  end

  def verify_email
    @invite_for = params[:invite_for]
    @token = params[:token]
    case @invite_for
    when 'retro' then @board = Retro::Board.get_board_by_invitation_token(@token)
    when 'poker' then @board = Poker::Board.get_board_by_invitation_token(@token)
    else
      @invalid = true
      flash[:alert] = "Invalid invite link"
    end
    show_otp_error("Invalid OTP") and return if params[:otp].blank? || params[:otp].size > 8
    guest = Guest.where(id: cookies.encrypted[:temp_gid], parent_user_id: @board.created_by).where("email_otp_sent_at >= ?", 15.minutes.ago).take
    show_invitation_error("Invalid invite link") and return unless guest.present?
    computed_otp = OpenSSL::HMAC.hexdigest('sha1', Rails.application.credentials.SALT, "#{params[:otp].strip}:#{guest.id}")
    show_otp_error("Invalid OTP") and return unless guest.email_otp == computed_otp
    sign_out(current_user) if current_user
    cookies.encrypted[:guest_id] = guest.id
    cookies.delete(:temp_gid)
    case @board.class.to_s
    when "Poker::Board"
      participant = Poker::Participant.where(board: @board, participant: guest, is_spectator: false).first_or_create!
      PokerBoardChannel.broadcast_to(@board,  {status: true, type: 'new_participant', participant: { id: participant.id, email: participant.participant.email, name: participant.participant.name } })
      redirect_to "/poker/board/#{@board.id}"
    when "Retro::Board"
      participant = Retro::Participant.where(board: @board, participant: guest).first_or_create!
      RetroBoardChannel.broadcast_to(@board,  {status: true, type: "new_participant", name: guest.name, id: guest.id, participant_id: participant.id })
      redirect_to retro_board_path(@board.id)
    else
      show_invitation_error("Invalid invitation link") and return
    end
  end

  def continue_as_existing_guest
    redirect_to "/" unless current_resource.present?
    @invite_for = params[:invite_for]
    @token = params[:token]
    case @invite_for
    when 'retro' then @board = Retro::Board.get_board_by_invitation_token(@token)
    when 'poker' then @board = Poker::Board.get_board_by_invitation_token(@token)
    else
      @invalid = true
      flash[:alert] = "Invalid invite link"
    end
    case @board.class.to_s
    when "Poker::Board"
      participant = Poker::Participant.where(board: @board, participant: current_resource, is_spectator: false).first_or_create!
      PokerBoardChannel.broadcast_to(@board,  {status: true, type: 'new_participant', participant: { id: participant.id, email: participant.participant.email, name: participant.participant.name } })
      redirect_to "/poker/board/#{@board.id}"
    when "Retro::Board"
      participant = Retro::Participant.where(board: @board, participant: current_resource).first_or_create!
      RetroBoardChannel.broadcast_to(@board,  {status: true, type: "new_participant", name: current_resource.name, id: current_resource.id, participant_id: participant.id })
      redirect_to retro_board_path(@board.id)
    else
      show_invitation_error("Invalid invitation link") and return
    end
  end

  def exit
    cookies.delete(:guest_id)
    redirect_to '/dashboard'
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :email)
  end

  def show_invitation_error(error)
    flash[:alert] = error
    redirect_to new_guest_path(token: params[:token], invite_for: params[:invite_for])
  end

  def show_otp_error(error)
    flash[:alert] = error
    redirect_to create_guest_path(token: params[:token], invite_for: params[:invite_for])
  end

  def validate_guest_params
    if guest_params[:email].blank? && guest_params[:name].blank?
      show_invitation_error("Both name and email are empty") and return false
    elsif guest_params[:email].blank?
      show_invitation_error("Email is empty") and return false
    elsif guest_params[:name].blank?
      show_invitation_error("Name is empty") and return false
    elsif !Mail::Address.new(guest_params[:email]).domain.present?
      show_invitation_error("Invalid email address") and return false
    end
    return true
  end

  def get_board_from_token(invite_for, token)
    case invite_for
    when 'retro' then return Retro::Board.get_board_by_invitation_token(token)
    when 'poker' then return Poker::Board.get_board_by_invitation_token(token)
    else show_invitation_error("Invalid invite link") and return nil
    end
  end

  def create_signature(token, name, email, otp)
    otp = (rand * 1000000).to_i
    signature_token = Base64.encode64("#{name}:#{email}:#{Time.zone.now.to_i}:#{token}:#{otp}")
    signature = OpenSSL::HMAC.hexdigest('sha1', Rails.application.credentials.SALT, signature_token)
    new_token = Base64.encode64("#{name}:#{email}:#{Time.zone.now.to_i}:#{token}:#{signature}")
    return [new_token, signature]
  end

  def verify_signature(token, otp)
    name, email, timestamp, token, signature = Base64.decode64(token)&.split(":")
    signature_token = Base64.encode64("#{name}:#{email}:#{timestamp}:#{token}:#{otp}")
    computed_token = OpenSSL::HMAC.hexdigest('sha1', Rails.application.credentials.SALT, "#{token}:#{otp}")
    computed_token == signature_token
  end

  def show_complete_profile_error(error, redirect_to_complete_profile=false)
    flash[:alert] = error
    redirect_to redirect_to_complete_profile ? complete_path(signature: params[:signature]) : "/"
  end
  
end

app/views/guests/get_otp.html.slim
.container.mx-auto.flex.justify-center.items-center.h-full.flex-col style="top: 10vh"
  .text-2xl.font-bold.inline-block = @board.name
  .text-gray-500 
    - if @invite_for == "retro"
      span Retrospective
    - elsif @invite_for == "poker"
      span Planning poker
  .session-container.shadow.p-7.mt-5
    - if flash[:alert].present?
      .w-full.rounded.bg-red-100.p-3.mb-2.border.border-red-400
        p.m-0 = flash[:alert]
    - if !@invalid && @board.present?
      = form_tag create_guest_path(invite_for: @invite_for, token: @token) do
        .w-full.mt-2
          p.mb-2 = "Please enter the one-time-password (OTP) that we sent you to the given email #{@guest.email}"
          input type="text" name="otp" class='bg-white border border-gray-400 w-full rounded p-3 outline-none' placeholder="Please check your email"
        .w-full.mt-5
          button.w-full.bg-green-500.text-white.rounded.font-medium.py-3 Join board
      

app/views/guests/get_profile.html.slim
.container.mx-auto.flex.justify-center.items-center.h-full.flex-col style="top: 10vh"
  .text-2xl.font-bold.inline-blockComplete Complete your profile
  .session-container.shadow.p-7.mt-5
    - if flash[:alert].present?
      .w-full.rounded.bg-red-100.p-3.mb-2.border.border-red-400
        p.m-0 = flash[:alert]
    = form_tag complete_path do
      = hidden_field_tag "signature", @signature
      .w-full.mt-2
        p.font-medium.mb-1 Your name
        input type="text" name="name" class='bg-white border border-gray-400 w-full rounded p-3 outline-none' placeholder="Eg. Monica"
        p.font-medium.mb-1.mt-4 Email
        input type="text" style="cursor: not-allowed" disabled="disabled" class='bg-gray-100 border border-gray-400 w-full rounded p-3 outline-none' value=@resource.email
      .w-full.mt-5
        button.w-full.bg-green-500.text-white.rounded.font-medium.py-3 Update
      

app/views/guests/new.html.slim
.container.mx-auto.flex.justify-center.items-center.h-full.flex-col style="top: 10vh"
  .text-2xl.font-bold.inline-block = @board.name
  .text-gray-500 
    - if @invite_for == "retro"
      span Retrospective
    - elsif @invite_for == "poker"
      span Planning poker
  .session-container.shadow.p-7.mt-5
    - if flash[:alert].present?
      .w-full.rounded.bg-red-100.p-3.mb-2.border.border-red-400
        p.m-0 = flash[:alert]
    - if !@invalid && @board.present?
      = form_tag new_guest_path(invite_for: @invite_for, token: @token) do
        .w-full.mt-2
          p.mb-1 Name
          input type="text" name="guest[name]" class='bg-white border border-gray-400 w-full rounded p-3 outline-none' placeholder=t('name_hint')
        .w-full.mt-2
          p.mb-1 Email
          input type="email" name="guest[email]" class='bg-white border border-gray-400 w-full rounded p-3 outline-none' placeholder=t('email_hint')
        p.text-sm.text-gray-500.mt-1 We ask your email so that you can use this email to see all the retrospectives you participated in the past and also we can remind you about the action items assigned to you
        .w-full.mt-5
          button.w-full.bg-green-500.text-white.rounded.font-medium.py-3 Next
    - if current_resource.present? && current_resource.class == Guest
      .w-full.mt-5.border-t.border-gray-300.pt-2.5.text-center
        = link_to continue_as_existing_guest_path(invite_for: @invite_for, token: @token) do
          .w-full.h-full.hover:bg-green-50.py-2.5.rounded.cursor-pointer.mt-2.transition-colors
            p.m-0.text-green-500.font-medium = "Continue as #{current_resource.name} to #{@board.name}"
            p.m-0.text-gray-500.text-sm = current_resource.email